import React from "react";
import { Avatar, Table } from "@mantine/core";
import { useNavigate } from "react-router-dom";

const Payslip = () => {
  const [active, setActive] = React.useState<"administrator" | "staff">(
    "administrator"
  );
  
  const navigate = useNavigate()
  const rows = [
    {
      id: 1,
      full_name: "Haylie Madsen",
      email: "ab@xyz.com",
      phone_number: "08156431267",
      role: "08156431267",
      salary: 239500,
      date_joined: "06 - 06 - 2010",
    },
    {
      id: 2 ,
      full_name: "Haylie Madsen",
      email: "ab@xyz.com",
      phone_number: "08156431267",
      role: "08156431267",
      salary: 239500,
      date_joined: "06 - 06 - 2010",
    },
    {
      id: 3,
      full_name: "Haylie Madsen",
      email: "ab@xyz.com",
      phone_number: "08156431267",
      role: "08156431267",
      salary: 239500,
      date_joined: "06 - 06 - 2010",
    },
    {
      id: 4,
      full_name: "Haylie Madsen",
      email: "ab@xyz.com",
      phone_number: "08156431267",
      role: "08156431267",
      salary: 239500,
      date_joined: "06 - 06 - 2010",
    },
  ];
  return (
    <div className="max-w-[1300px] mx-auto py-10">
      <div className="flex gap-5">
        <div
          className={`text-base font-medium cursor-pointer ${
            active === "administrator"
              ? "border-b-4 border-dakeb-green-dark text-[#4F4F4F]"
              : "text-[#828282]"
          }`}
          onClick={() => setActive("administrator")}
        >
          Administrator
        </div>
        <div
          className={`text-base font-medium cursor-pointer ${
            active === "staff"
              ? "border-b-4 border-dakeb-green-dark text-[#4F4F4F]"
              : "text-[#828282]"
          }`}
          onClick={() => setActive("staff")}
        >
          Staff
        </div>
      </div>

      <div className="mt-10">
        <Table>
          <thead>
            <tr>
              <th className="!border-none">Generated by</th>
              <th className="!border-none">Pay period</th>
              <th className="!border-none">Gross earnings</th>
              <th className="!border-none">Deductions</th>
              <th className="!border-none">Net pay</th>
              <th className="!border-none">Pay date</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.id}>
                <td>
                  <div className="flex gap-2 items-center">
                    <Avatar
                      src={null}
                      alt="Profile Picture"
                      color="red"
                      size={40}
                      radius={40}
                    >
                      VR
                    </Avatar>
                    <div>{row.full_name}</div>
                  </div>
                </td>
                <td>{row.email}</td>
                <td>{row.phone_number}</td>
                <td>{row.role}</td>
                <td>{row.salary}</td>
                <td>{row.date_joined}</td>
                <td>
                  <button className="text-dakeb-green-mid font-bold"
                  onClick={() => navigate(`/pay-slip/${row.id}`)}>
                    View
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </Table>
      </div>
    </div>
  );
};

export default Payslip;
